In [3]:
import numpy as np
import pandas as pd
import cv2

numcam_data = pd.read_csv("D:\TRABAJOS RICARDO\Semestre_13\PFG\Repositorio\manual_annotations\CAMERA.csv", sep= ";")
position_data = pd.read_csv("D:\TRABAJOS RICARDO\Semestre_13\PFG\Repositorio\manual_annotations\DATA.csv", sep= ";")


In [4]:
camara_days = []
position_days = []

sub_arrays = np.split(np.transpose(position_data.values), [32*7,62*7])
for i, _ in enumerate(sub_arrays):
    position_days.append(np.transpose(sub_arrays[i]))

sub_arrays = np.split(np.transpose(numcam_data.values), [32,62])
for i, _ in enumerate(sub_arrays):
    camara_days.append(np.transpose(sub_arrays[i]))

#print(camara_days[2].shape)
#print(position_days[2].shape)

In [323]:
def framebyframe(actual_list):
    camara_list = []
    positions_list = []

    #print(actual_list)

    for column in range(actual_list.shape[1]):
        camara_list.append(actual_list.values[:,column])

    camara_list = np.array(camara_list)
    
    for i in camara_list:
        print(i[0])

    #for column in range(position_data.shape[1]//7):
    #    positions_list.append(position_data.values[:,7*column:7*column+5])
    #    
    #print(positions_list[1])
a = pd.DataFrame(position_days[0])
print(a)
data2camday(a)


         0    1    2    3    4    5    6      7    8    9    ...  214  215  \
0          0  257    0  390   81    0    0      0  441    2  ...  214    0   
1          1  257    0  390   80    0    0      1  441    1  ...  214    0   
2          2  257    0  390   80    0    0      2  441    1  ...  214    0   
3          3  257    0  390   80    0    0      3  441    1  ...  214    0   
4          4  257    0  390   80    0    0      4  441    1  ...  214    0   
...      ...  ...  ...  ...  ...  ...  ...    ...  ...  ...  ...  ...  ...   
35995  35995  439  278  584  404    0    0  35995  399   25  ...   90    0   
35996  35996  439  278  584  404    0    0  35996  399   25  ...   90    0   
35997  35997  439  278  584  404    0    0  35997  399   25  ...   90    0   
35998  35998  439  278  584  404    0    0  35998  399   25  ...   90    0   
35999  35999  439  278  584  404    0    0  35999  399   25  ...   90    0   

       216    217  218  219  220  221  222  223  
0        0   

In [14]:
input_url = "D:\TRABAJOS RICARDO\Semestre_13\PFG\Github\Entrenamiento-Maestro-Estudiante\Acondicionamiento imagenes\Frames\Entradas"
output_url = "D:\TRABAJOS RICARDO\Semestre_13\PFG\Github\Entrenamiento-Maestro-Estudiante\Acondicionamiento imagenes\Frames\Salidas"

def process_dayx_camx_framex(day2process, cam2process):
    day_cam_info = pd.DataFrame(camara_days[day2process-1])
    day_position_info = pd.DataFrame(position_days[day2process-1])

    for frame_num, frame_content in enumerate(day_cam_info.values):
        
        if frame_num % 20 == 0:

            for actual_person, camara_num in enumerate(frame_content):
                
                if camara_num == cam2process:
                    #print(frame_num, cam2process, day2process, actual_person)
                    positions = (day_position_info.values[frame_num,7*actual_person+1:7*actual_person+5])
                    
                    # read the image
                    img = cv2.imread(input_url + "\Day" + str(day2process) + "\Cam" + str(cam2process) + "\frame00000.png")
                    cv2.rectangle(img, (positions[0], positions[1]), (positions[2], positions[3]), (0, 255, 0), 2)
                    cv2.imwrite(output_url + "\Day" + str(day2process) + "\Cam" + str(cam2process) + "\frame00000.png", img)

process_dayx_camx_framex(day2process=1, cam2process=1)

[441   2 583 182]
[ 63 245 256 382]
[635   0 787 163]
[630 311 817 499]
[178   0 329 154]
[184 369 355 491]
[293   0 435 160]
[ 71  89 254 247]
[358 327 512 513]
[198 204 401 362]
[787 326 940 495]
[778  58 913 214]
[442   1 584 181]
[ 63 245 256 382]
[635   0 787 163]
[630 310 817 498]
[178   0 329 154]
[183 369 354 491]
[293   0 435 160]
[ 71  89 254 247]
[358 334 512 520]
[196 204 399 362]
[784 331 937 500]
[782  58 917 214]
[443   1 585 181]
[ 63 245 256 382]
[635   1 787 164]
[630 310 817 498]
[178   0 329 154]
[182 369 353 491]
[293   0 435 160]
[ 71  89 254 247]
[358 342 512 527]
[194 204 397 362]
[781 337 934 506]
[787  58 922 214]
[445   0 587 180]
[ 63 245 256 382]
[635   1 787 164]
[630 310 817 498]
[178   0 329 154]
[181 369 352 491]
[293   0 435 160]
[ 71  89 254 247]
[358 343 512 528]
[192 204 395 362]
[780 339 933 508]
[791  58 926 214]
[446   0 588 180]
[ 63 245 256 382]
[635   2 787 165]
[630 310 817 498]
[178   0 329 154]
[180 369 351 491]
[294   0 436 160]
[ 71  89 2